import type { CanvasBlendMode, GrainPreset, PresetId } from './types';

export const PRESETS: Record<PresetId, GrainPreset> = {
  'itonics-neutral': {
    id: 'itonics-neutral',
    label: 'Itonics Neutral',
    background: '#fdfdfd',
    colors: ['#fdfdfd', '#a6a6a6', '#a6a6a6', '#fdfdfd', '#fdfdfd'],
    defaultBlendMode: 'source-over',
    defaultGrainOpacity: 0.35,
    defaults: {
      background: '#fdfdfd',
      colors: ['#fdfdfd', '#a6a6a6', '#a6a6a6', '#fdfdfd', '#fdfdfd'],
      sectionHeightVh: 100,
      shapeStyle: 'center',
      maxDpr: 3,
      paused: false,
      speed: 0.6,
      motionIntensity: 2.75,
      grainOpacity: 0.35,
      centerBlobScale: 1,
      centerOffsetX: 0,
      centerOffsetY: 0,
      blendMode: 'source-over',
      fullCanvasGradient: false,
      mouseInteraction: false,
      mouseMode: 'repel',
      mouseStrength: 1,
      mouseRadius: 240,
      blobCount: 5,
      blurPx: 110,
    },
  },
  'luna-dark-center-blob': {
    id: 'luna-dark-center-blob',
    label: 'Luna Dark Center Blob',
    background: '#1d1d1d',
    colors: ['#1d1d1d', '#5a5a5a', '#5a5a5a', '#1d1d1d', '#1d1d1d'],
    defaultBlendMode: 'source-over',
    defaultGrainOpacity: 0.35,
    defaults: {
      background: '#1d1d1d',
      colors: ['#1d1d1d', '#5a5a5a', '#5a5a5a', '#1d1d1d', '#1d1d1d'],
      sectionHeightVh: 100,
      shapeStyle: 'center',
      maxDpr: 3,
      paused: false,
      speed: 0.6,
      motionIntensity: 2.75,
      grainOpacity: 0.35,
      centerBlobScale: 1,
      centerOffsetX: 0,
      centerOffsetY: 0,
      blendMode: 'source-over',
      fullCanvasGradient: false,
      mouseInteraction: false,
      mouseMode: 'repel',
      mouseStrength: 1,
      mouseRadius: 240,
      blobCount: 5,
      blurPx: 110,
    },
  },
};

export const PRESET_ORDER: PresetId[] = ['itonics-neutral', 'luna-dark-center-blob'];

export const CANVAS_BLEND_MODES: ReadonlyArray<{ value: CanvasBlendMode; label: string }> = [
  { value: 'source-over', label: 'Source Over' },
  { value: 'lighter', label: 'Lighter' },
  { value: 'screen', label: 'Screen' },
  { value: 'overlay', label: 'Overlay' },
  { value: 'multiply', label: 'Multiply' },
  { value: 'soft-light', label: 'Soft Light' },
  { value: 'hard-light', label: 'Hard Light' },
  { value: 'color-dodge', label: 'Color Dodge' },
  { value: 'difference', label: 'Difference' },
  { value: 'exclusion', label: 'Exclusion' },
];
